FROM mcr.microsoft.com/dotnet/aspnet:9.0
WORKDIR /app

# Copia solo los archivos publicados
COPY ./publish .

# Configuración del entorno
ENV ASPNETCORE_URLS=http://+:5120
ENV ASPNETCORE_ENVIRONMENT=Development
EXPOSE 5120

ENTRYPOINT ["dotnet", "WebApi1.dll"]