
services:
  app1:
    image: api-tareas
    ports:
      - "4000:5120"
    networks:
      - app_network

  app2:
    image: api-tareas
    ports:
      - "4001:5120"
    networks:
      - app_network
    
  app3:
    image: api-tareas
    ports:
      - "4002:5120"
    networks:
      - app_network

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app1
      - app2
      - app3
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
